meta_product_name: "Lemonade Stand"
meta_title: "Lemonade Stand - Seamless Transactions for Makers"
meta_description: "Lemonade Stand is the go-to app for makers to effortlessly manage transactions and track orders at physical pop-up events. Simplify your sales process and focus on what you do best — creating amazing products."
meta_image: "lemonadestand_meta.png" # should exist in `app/assets/images/`
